### ISSUE TITLE
Slider Geri Butonu Gözükmüyor

### ISSUE THREAD

**Issue by atakangktepe** [interacthings/iett-geri-bildirim#12]
Ana sayfada ki slider'ın geri butonu gözükmüyor.

**Comment by ademilter** [comment]
slider alanı komple değişti. yakında yenilenecek :+1: 

![screen shot 2015-10-01 at 15 51 09](https://cloud.githubusercontent.com/assets/187922/10221037/494f02e4-6854-11e5-9594-ff0bd7f7bfee.png)
