### ISSUE TITLE
Nasıl Giderim Sayfası Pencere Hatası

### ISSUE THREAD

**Issue by serkanince** [interacthings/iett-geri-bildirim#15]
Hat gidilecek yere göre seçildi fakat sonuçtan sonra sol pencere uçtu.

![image](https://cloud.githubusercontent.com/assets/3519243/10227268/00e7e2b6-6875-11e5-9da7-45d0c56d08c2.png)

**Comment by ademilter** [comment]
bu sayfa bizim kontrolümüzde değil
