### ISSUE TITLE
İstanbul Kart Başvuru Seçimi

### ISSUE THREAD

**Issue by ozziest** [interacthings/iett-geri-bildirim#3]
Varsayılan olarak başvuru seçin geliyor. Doğrudan "Bilgi ve Online Başvuru" butonuna tıkladığımızda hiç bir işlem yapılmıyor. O bölümde "Seçiniz" aktifken butona basıldığında seçim için ufak bir uyarı mesajı çıkabilirse şahane olur.

**Comment by ademilter** [comment]
animate.css kütüphanesinden **[ta-da efekti](https://github.com/daneden/animate.css/blob/master/animate.css#L374)** kullanılarak, önce seçimin yapılmasına dikkat çekildi.

[![screen shot 2015-10-01 at 14 51 27](https://cloud.githubusercontent.com/assets/187922/10219949/f76b1cb8-684b-11e5-88e0-8e6c1a7a403c.png)](http://d.pr/v/1kffJ)
